title: Hugo Starter
defaultContentLanguage: en
canonifyURLs: true
enableGitInfo: true

permalinks:
  /: /:sections/:slug/

outputs:
  home: ["HTML", "RSS"]

imaging:
  quality: 95

timeout: 1000000

params:
  github_repo: "https://github.com/rickdaalhuizen90/rickdaalhuizen.com"


markup:
  goldmark:
    renderer:
      unsafe: true
